### PR TITLE
docs: add collected lua scripts

### PR DESCRIPTION
**Pull request by chemelli74**

### CODE REVIEW

**Comment by chemelli74** [comment]
@rokam any change to get this merged ? ;-)

**Review by rokam — APPROVED** [review]

**Comment by chemelli74** [comment]
@rokam seems you are not recognised any more as part admin of this repo for some reason.
You know what may happened ?

**Comment by rokam** [comment]
I'm not part of midea-lan anymore. Try it with @wuwentao

**Comment by chemelli74** [comment]
Hi everyone, just to understand: should I invest my time and work on this project or not ?

**Review by wuwentao — APPROVED** [review]

**Comment by wuwentao** [comment]
> Hi everyone, just to understand: should I invest my time and work on this project or not ?

I'm currently on vacation, sorry for the delay, approved this PR.

most of these github repos is open source , everybody can read and get all the source code.
I don't think we are working for anyone, also like the origin author georgezhao2010.
I'm always expected we can have more contributors, and we should really work like a team.
in addition, I'm not sure with what we expected, but I have share all the info to us.

**Comment by audunmg** [comment]
Suggestion: Since different vendors might have the same name for different lua script, could you add the lua scripts in a subdirectory?

**Pull request merged**
